"""Planner parity: the Python agent's plan() must reproduce the JS agent's
plan() recording byte-for-byte on real levels.

The golden vectors (tests/golden/vectors.json) include the JS agent's own
plan() recordings on three real levels (tutorial, simple, above_ground),
generated by driving the real JS planner (tools/gen_golden.mjs). Here we run
the PYTHON planner over the same parsed levels and assert the emitted
recording is identical event-for-event. Because the recording is identical
and the Python adapter is frame-parity-exact with the JS engine (see
test_parity.py), the Python agent solves these levels exactly as the JS
agent does.
"""

import json
from pathlib import Path

import pytest

from agent_adapter import py_adapter
from agent_planner import plan, simulate
from agent_planner import test_level as solve_level  # aliased: pytest collects test_*

GOLDEN = json.loads((Path(__file__).parent / "golden" / "vectors.json").read_text())
# The JS legend's role map, emitted into the vectors so glyph->role mapping
# can't drift between the two sides.
LEGEND = GOLDEN["roles"]
AGENT_CASES = [c for c in GOLDEN["cases"] if c["kind"] == "agent"]


@pytest.mark.parametrize("case", AGENT_CASES, ids=[c["name"] for c in AGENT_CASES])
def test_python_plan_matches_js_recording(case):
    parsed = {"grid": case["grid"], "meta": case["meta"]}
    result = plan(parsed, LEGEND, adapter=py_adapter)
    assert result["recording"] == case["recording"], (
        f"{case['name']}: Python plan() diverged from JS plan() recording"
    )


@pytest.mark.parametrize("case", AGENT_CASES, ids=[c["name"] for c in AGENT_CASES])
def test_python_plan_recording_wins(case):
    """The recording the Python planner emits actually solves the level when
    replayed through the Python adapter, ending on the golden final frame."""
    parsed = {"grid": case["grid"], "meta": case["meta"]}
    result = plan(parsed, LEGEND, adapter=py_adapter)
    sim = simulate(py_adapter, parsed, LEGEND, recording=result["recording"], max_frames=case["maxFrames"])
    golden_last = case["frames"][-1]
    assert sim["outcome"] == golden_last["phase"]
    assert sim["score"] == golden_last["score"]


@pytest.mark.parametrize("case", AGENT_CASES, ids=[c["name"] for c in AGENT_CASES])
def test_level_solves_real_levels(case):
    """End-to-end: test_level returns ok with at least one solution."""
    parsed = {"grid": case["grid"], "meta": case["meta"]}
    result = solve_level(parsed, LEGEND, adapter=py_adapter)
    # Only assert solvability for cases whose golden run actually won.
    if case["frames"][-1]["phase"] == "won":
        assert result["ok"] is True
        assert len(result["solutions"]) >= 1
        assert result["solution"]["recording"] == result["solutions"][0]["recording"]
